name = "Immersion Cigs Hotfix"
prefix = "zrn_cig_hotfix"
mainprefix = "z"

[properties]
author = "MrZorn"
url = "https://github.com/PulsarNeutronStar/Immersion-Cigs-Hotfix"


[files]
include = [
    "mod.cpp",      # These files are copied to the build directory by default
    "meta.cpp",     # They do not need to be added to your list
    "LICENSE",
    "*.paa",
    "*.bikey"
]
exclude = [
    "*.psd",        # By default this list is empty
    "*.md",
    "/.vscode/",
]

[version]

git_hash = 0


[hemtt.launch.default]
workshop = [
    "450814997",  # CBA_A3's Workshop ID
    "463939057",  # ACE3
    "2369477168", # Advanced Developer Tools
    "753946944",  # Immersive Cigs Original
]

dlc = [
]

optionals = [
]

parameters = [
    "-filePatching",
    "-window",
    "-noPause",
    "-noPauseAudio",
]

executable = "arma3_x64"        # Default: "arma3_x64"

[hemtt.launch.test]
mission = "test-immersive-cigs-hotfix.Stratis"
workshop = [
    "450814997", # CBA_A3's Workshop ID
    "463939057", # ACE3
    "2369477168", # Advanced Developer Tools
    "753946944",  # Immersive Cigs Original
]
parameters = [
    "-filePatching",
    "-window",
    "-noPause",
    "-noPauseAudio",
]
dlc = [
]
optionals = [
]
